### PR TITLE
Update common band names table

### LINKED ISSUE #19: Add rededge1,2,3 to common names
It's a bit weird that the common name `rededge` has 3 bands included for S2, which is not ideal if you try to identify bands based on the common names.
The great repository [Awesome Spectral Indices](https://github.com/awesome-spectral-indices/awesome-spectral-indices#expressions) splits the rededge into 3 parts: Red Edge 1, 2 and 3.
I'd propose to add these three in addition.

### PR DESCRIPTION
**Pull request by m-mohr**
Implements #19

### CODE REVIEW

**Review by emmanuelmathot — COMMENTED** [review]
This is a discrepancy regarding existing splitted CBN (e.g. nir08, nir09, swir16, swir22)
Either we keep splitting the common band with names based on their subranges or we use agnostic division number as in https://github.com/awesome-spectral-indices/awesome-spectral-indices#expressions.
The former is not ideal since all instruments do not share the same wavelengths division but has the advantage of a semantic information in the band name.
The latter is more flexible but we loose an information and in addition this would be a breaking change for future versions.

Personally, I'd rather keep the subrange information in the CBN.

**Comment by m-mohr** [comment]
So my use case is exactly "Awesome Spectral Indices". I'd like to apply a spectral index from the list to data and just get the correct assets (bands) from the metadata based on the common name (or wavelength, if no common name is present). This only works right now if the formula doesn't include a rededge1,2,3 band. The overlapping wavelengths (and CBNs) are an issue though.

**Comment by emmanuelmathot** [comment]
I understand you requirement, I have the same since 2 years and I even needed new bands to be added in the CBN list. I pushed a [PR at that time](https://github.com/radiantearth/stac-spec/pull/1054). Beyond the fact that the rule is that any new CBN must be shared by 3 or more other satellites, my comment here is more about the consistency of the nomenclature we adopt. Either a simple division number or an average wavelength number suffix (e.g. rededge70, rededge75).

**Comment by philvarner** [comment]
S2 red bands are:
- B05 | Vegetation red edge, 704.1 nm (S2A), 703.8 nm (S2B) | 20m
- B06 | Vegetation red edge, 740.5 nm (S2A), 739.1 nm (S2B) | 20m
- B07 | Vegetation red edge, 782.8 nm (S2A), 779.7 nm (S2B) | 20m

**Comment by m-mohr** [comment]
Meeting notes: Needs a broader discussion, but rededge1-3 are not consistent with e.g. nir08 etc so we may want to change then to e.g. regedge70, rededge75 etc (as proposed by Emmanuel above). For this it would also be useful to know how other satellites do it and which bands they have. So I'll look that up and propose a name. Also we should check with ASI how they differentiate.

**Comment by davemlz** [comment]
Hey! Sorry to just jump into the discussion. @m-mohr opened and Issue in ASI (https://github.com/awesome-spectral-indices/awesome-spectral-indices/issues/30) (I just renamed it), and it would be cool to have the mapping from the ASI standard to this standard. So, just to give you an overview, the bands and their standard in ASI were selected according to bands required by specific spectral indices (a band in a specific index shouldn't be ambiguous). E.g., in the case of Sentinel-2, there are indices that require the three red edge bands (see [IRECI](https://doi.org/10.1016/j.isprsjprs.2013.04.007) = `(RE3 - R) / (RE1 / RE2)`) -> This index couldn't be computed if the red edge bands were just a common unique band.

**Comment by m-mohr** [comment]
Interesting resource: https://eoreader.readthedocs.io/en/v0.19.1/optical_band_mapping.html

**Review by emmanuelmathot — APPROVED** [review]

**Comment by m-mohr** [comment]
@davemlz: What do you think about the current state? I've tried to find a compromise here that hopefully works for ASI and STAC equally well.

**Review by emmanuelmathot — APPROVED** [review]

**Comment by m-mohr** [comment]
Actually, I think we can merge this and update it during the beta if needed.

**Comment by davemlz** [comment]
Wow! Thank your for this!

@m-mohr this looks perfect. I will update the mapping from ASI to eo ;)

**Comment by davemlz** [comment]
https://github.com/awesome-spectral-indices/awesome-spectral-indices/commit/35d75efcecb49b016ba28c6df420200556e0a9f8 Done ;)

**Pull request merged**
